### ISSUE TITLE
Ping timeout (wrong reply?)

### ISSUE THREAD

**Issue by qywx** [mpthompson/stm32_f4_ptpd#2]
I have met problem while pinging my Discovery+DP83848.
    `ping 192.168.137.54`
says timeout. But Wireshark can see ICMP packets. It seems request is wrong.

Screenshot
![screenshot](https://www.dropbox.com/s/l5mnqhqndjw0smy/ping%20fail.jpg?dl=1)

**Comment by mpthompson** [comment]
I believe this is resolved in commit fcd4e0f on Mar 29, 2017.
